server {
    listen 80;

    # Sirve los archivos estáticos del dist
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # necesario para React Router
    }

    # Redirige las llamadas a la API al contenedor del servidor
    location /api/ {
        proxy_pass http://server:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}